// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/cristiano-pacheco/pingo/internal/modules/identity/event"
	mock "github.com/stretchr/testify/mock"
)

// MockUserCreatedProducerI is an autogenerated mock type for the UserCreatedProducerI type
type MockUserCreatedProducerI struct {
	mock.Mock
}

type MockUserCreatedProducerI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCreatedProducerI) EXPECT() *MockUserCreatedProducerI_Expecter {
	return &MockUserCreatedProducerI_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function with given fields: ctx, message
func (_m *MockUserCreatedProducerI) Produce(ctx context.Context, message event.UserCreatedMessage) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.UserCreatedMessage) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserCreatedProducerI_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockUserCreatedProducerI_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - message event.UserCreatedMessage
func (_e *MockUserCreatedProducerI_Expecter) Produce(ctx interface{}, message interface{}) *MockUserCreatedProducerI_Produce_Call {
	return &MockUserCreatedProducerI_Produce_Call{Call: _e.mock.On("Produce", ctx, message)}
}

func (_c *MockUserCreatedProducerI_Produce_Call) Run(run func(ctx context.Context, message event.UserCreatedMessage)) *MockUserCreatedProducerI_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.UserCreatedMessage))
	})
	return _c
}

func (_c *MockUserCreatedProducerI_Produce_Call) Return(_a0 error) *MockUserCreatedProducerI_Produce_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserCreatedProducerI_Produce_Call) RunAndReturn(run func(context.Context, event.UserCreatedMessage) error) *MockUserCreatedProducerI_Produce_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserCreatedProducerI creates a new instance of MockUserCreatedProducerI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCreatedProducerI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCreatedProducerI {
	mock := &MockUserCreatedProducerI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
