// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/cristiano-pacheco/pingo/internal/modules/identity/event"
	mock "github.com/stretchr/testify/mock"
)

// MockUserUpdatedProducer is an autogenerated mock type for the UserUpdatedProducer type
type MockUserUpdatedProducer struct {
	mock.Mock
}

type MockUserUpdatedProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUpdatedProducer) EXPECT() *MockUserUpdatedProducer_Expecter {
	return &MockUserUpdatedProducer_Expecter{mock: &_m.Mock}
}

// Produce provides a mock function with given fields: ctx, message
func (_m *MockUserUpdatedProducer) Produce(ctx context.Context, message event.UserUpdatedMessage) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.UserUpdatedMessage) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserUpdatedProducer_Produce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Produce'
type MockUserUpdatedProducer_Produce_Call struct {
	*mock.Call
}

// Produce is a helper method to define mock.On call
//   - ctx context.Context
//   - message event.UserUpdatedMessage
func (_e *MockUserUpdatedProducer_Expecter) Produce(ctx interface{}, message interface{}) *MockUserUpdatedProducer_Produce_Call {
	return &MockUserUpdatedProducer_Produce_Call{Call: _e.mock.On("Produce", ctx, message)}
}

func (_c *MockUserUpdatedProducer_Produce_Call) Run(run func(ctx context.Context, message event.UserUpdatedMessage)) *MockUserUpdatedProducer_Produce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.UserUpdatedMessage))
	})
	return _c
}

func (_c *MockUserUpdatedProducer_Produce_Call) Return(_a0 error) *MockUserUpdatedProducer_Produce_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserUpdatedProducer_Produce_Call) RunAndReturn(run func(context.Context, event.UserUpdatedMessage) error) *MockUserUpdatedProducer_Produce_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserUpdatedProducer creates a new instance of MockUserUpdatedProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUpdatedProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUpdatedProducer {
	mock := &MockUserUpdatedProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
