coverage:
  ignore:
    # Ignore specific folders
    - "cmd/**"
    - "docs/**"
    - "config/**"
    - "pkg/**"
    - "vendor/**"
    # Ignore all test files
    - "**/*_test.go"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
