// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPasswordValidatorI is an autogenerated mock type for the PasswordValidatorI type
type MockPasswordValidatorI struct {
	mock.Mock
}

type MockPasswordValidatorI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPasswordValidatorI) EXPECT() *MockPasswordValidatorI_Expecter {
	return &MockPasswordValidatorI_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: password
func (_m *MockPasswordValidatorI) Validate(password string) error {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPasswordValidatorI_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockPasswordValidatorI_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - password string
func (_e *MockPasswordValidatorI_Expecter) Validate(password interface{}) *MockPasswordValidatorI_Validate_Call {
	return &MockPasswordValidatorI_Validate_Call{Call: _e.mock.On("Validate", password)}
}

func (_c *MockPasswordValidatorI_Validate_Call) Run(run func(password string)) *MockPasswordValidatorI_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPasswordValidatorI_Validate_Call) Return(_a0 error) *MockPasswordValidatorI_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPasswordValidatorI_Validate_Call) RunAndReturn(run func(string) error) *MockPasswordValidatorI_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPasswordValidatorI creates a new instance of MockPasswordValidatorI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPasswordValidatorI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPasswordValidatorI {
	mock := &MockPasswordValidatorI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
