// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mailer "github.com/cristiano-pacheco/pingo/internal/shared/modules/mailer"
	mock "github.com/stretchr/testify/mock"
)

// MockSMTP is an autogenerated mock type for the SMTP type
type MockSMTP struct {
	mock.Mock
}

type MockSMTP_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSMTP) EXPECT() *MockSMTP_Expecter {
	return &MockSMTP_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, md
func (_m *MockSMTP) Send(ctx context.Context, md mailer.MailData) error {
	ret := _m.Called(ctx, md)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, mailer.MailData) error); ok {
		r0 = rf(ctx, md)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSMTP_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSMTP_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - md mailer.MailData
func (_e *MockSMTP_Expecter) Send(ctx interface{}, md interface{}) *MockSMTP_Send_Call {
	return &MockSMTP_Send_Call{Call: _e.mock.On("Send", ctx, md)}
}

func (_c *MockSMTP_Send_Call) Run(run func(ctx context.Context, md mailer.MailData)) *MockSMTP_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(mailer.MailData))
	})
	return _c
}

func (_c *MockSMTP_Send_Call) Return(_a0 error) *MockSMTP_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSMTP_Send_Call) RunAndReturn(run func(context.Context, mailer.MailData) error) *MockSMTP_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSMTP creates a new instance of MockSMTP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSMTP(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSMTP {
	mock := &MockSMTP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
