// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cristiano-pacheco/pingo/internal/modules/monitor/model"
	mock "github.com/stretchr/testify/mock"
)

// MockContactRepositoryI is an autogenerated mock type for the ContactRepositoryI type
type MockContactRepositoryI struct {
	mock.Mock
}

type MockContactRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContactRepositoryI) EXPECT() *MockContactRepositoryI_Expecter {
	return &MockContactRepositoryI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, contact
func (_m *MockContactRepositoryI) Create(ctx context.Context, contact model.ContactModel) (model.ContactModel, error) {
	ret := _m.Called(ctx, contact)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.ContactModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ContactModel) (model.ContactModel, error)); ok {
		return rf(ctx, contact)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ContactModel) model.ContactModel); ok {
		r0 = rf(ctx, contact)
	} else {
		r0 = ret.Get(0).(model.ContactModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ContactModel) error); ok {
		r1 = rf(ctx, contact)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContactRepositoryI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockContactRepositoryI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - contact model.ContactModel
func (_e *MockContactRepositoryI_Expecter) Create(ctx interface{}, contact interface{}) *MockContactRepositoryI_Create_Call {
	return &MockContactRepositoryI_Create_Call{Call: _e.mock.On("Create", ctx, contact)}
}

func (_c *MockContactRepositoryI_Create_Call) Run(run func(ctx context.Context, contact model.ContactModel)) *MockContactRepositoryI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ContactModel))
	})
	return _c
}

func (_c *MockContactRepositoryI_Create_Call) Return(_a0 model.ContactModel, _a1 error) *MockContactRepositoryI_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContactRepositoryI_Create_Call) RunAndReturn(run func(context.Context, model.ContactModel) (model.ContactModel, error)) *MockContactRepositoryI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, contactID
func (_m *MockContactRepositoryI) Delete(ctx context.Context, contactID uint64) error {
	ret := _m.Called(ctx, contactID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, contactID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContactRepositoryI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockContactRepositoryI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - contactID uint64
func (_e *MockContactRepositoryI_Expecter) Delete(ctx interface{}, contactID interface{}) *MockContactRepositoryI_Delete_Call {
	return &MockContactRepositoryI_Delete_Call{Call: _e.mock.On("Delete", ctx, contactID)}
}

func (_c *MockContactRepositoryI_Delete_Call) Run(run func(ctx context.Context, contactID uint64)) *MockContactRepositoryI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockContactRepositoryI_Delete_Call) Return(_a0 error) *MockContactRepositoryI_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContactRepositoryI_Delete_Call) RunAndReturn(run func(context.Context, uint64) error) *MockContactRepositoryI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockContactRepositoryI) FindAll(ctx context.Context) ([]model.ContactModel, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.ContactModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.ContactModel, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.ContactModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ContactModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContactRepositoryI_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockContactRepositoryI_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContactRepositoryI_Expecter) FindAll(ctx interface{}) *MockContactRepositoryI_FindAll_Call {
	return &MockContactRepositoryI_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockContactRepositoryI_FindAll_Call) Run(run func(ctx context.Context)) *MockContactRepositoryI_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockContactRepositoryI_FindAll_Call) Return(_a0 []model.ContactModel, _a1 error) *MockContactRepositoryI_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContactRepositoryI_FindAll_Call) RunAndReturn(run func(context.Context) ([]model.ContactModel, error)) *MockContactRepositoryI_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MockContactRepositoryI) FindByName(ctx context.Context, name string) (model.ContactModel, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 model.ContactModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.ContactModel, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.ContactModel); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(model.ContactModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContactRepositoryI_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockContactRepositoryI_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockContactRepositoryI_Expecter) FindByName(ctx interface{}, name interface{}) *MockContactRepositoryI_FindByName_Call {
	return &MockContactRepositoryI_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockContactRepositoryI_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockContactRepositoryI_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockContactRepositoryI_FindByName_Call) Return(_a0 model.ContactModel, _a1 error) *MockContactRepositoryI_FindByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContactRepositoryI_FindByName_Call) RunAndReturn(run func(context.Context, string) (model.ContactModel, error)) *MockContactRepositoryI_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, contact
func (_m *MockContactRepositoryI) Update(ctx context.Context, contact model.ContactModel) (model.ContactModel, error) {
	ret := _m.Called(ctx, contact)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.ContactModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ContactModel) (model.ContactModel, error)); ok {
		return rf(ctx, contact)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ContactModel) model.ContactModel); ok {
		r0 = rf(ctx, contact)
	} else {
		r0 = ret.Get(0).(model.ContactModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ContactModel) error); ok {
		r1 = rf(ctx, contact)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockContactRepositoryI_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockContactRepositoryI_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - contact model.ContactModel
func (_e *MockContactRepositoryI_Expecter) Update(ctx interface{}, contact interface{}) *MockContactRepositoryI_Update_Call {
	return &MockContactRepositoryI_Update_Call{Call: _e.mock.On("Update", ctx, contact)}
}

func (_c *MockContactRepositoryI_Update_Call) Run(run func(ctx context.Context, contact model.ContactModel)) *MockContactRepositoryI_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ContactModel))
	})
	return _c
}

func (_c *MockContactRepositoryI_Update_Call) Return(_a0 model.ContactModel, _a1 error) *MockContactRepositoryI_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockContactRepositoryI_Update_Call) RunAndReturn(run func(context.Context, model.ContactModel) (model.ContactModel, error)) *MockContactRepositoryI_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContactRepositoryI creates a new instance of MockContactRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContactRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContactRepositoryI {
	mock := &MockContactRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
