// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cristiano-pacheco/pingo/internal/modules/monitor/model"
	mock "github.com/stretchr/testify/mock"
)

// MockNotificationRepositoryI is an autogenerated mock type for the NotificationRepositoryI type
type MockNotificationRepositoryI struct {
	mock.Mock
}

type MockNotificationRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationRepositoryI) EXPECT() *MockNotificationRepositoryI_Expecter {
	return &MockNotificationRepositoryI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, notification
func (_m *MockNotificationRepositoryI) Create(ctx context.Context, notification model.NotificationModel) (model.NotificationModel, error) {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.NotificationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.NotificationModel) (model.NotificationModel, error)); ok {
		return rf(ctx, notification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.NotificationModel) model.NotificationModel); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Get(0).(model.NotificationModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.NotificationModel) error); ok {
		r1 = rf(ctx, notification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepositoryI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotificationRepositoryI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - notification model.NotificationModel
func (_e *MockNotificationRepositoryI_Expecter) Create(ctx interface{}, notification interface{}) *MockNotificationRepositoryI_Create_Call {
	return &MockNotificationRepositoryI_Create_Call{Call: _e.mock.On("Create", ctx, notification)}
}

func (_c *MockNotificationRepositoryI_Create_Call) Run(run func(ctx context.Context, notification model.NotificationModel)) *MockNotificationRepositoryI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.NotificationModel))
	})
	return _c
}

func (_c *MockNotificationRepositoryI_Create_Call) Return(_a0 model.NotificationModel, _a1 error) *MockNotificationRepositoryI_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepositoryI_Create_Call) RunAndReturn(run func(context.Context, model.NotificationModel) (model.NotificationModel, error)) *MockNotificationRepositoryI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, notificationID
func (_m *MockNotificationRepositoryI) FindByID(ctx context.Context, notificationID uint64) (model.NotificationModel, error) {
	ret := _m.Called(ctx, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.NotificationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.NotificationModel, error)); ok {
		return rf(ctx, notificationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.NotificationModel); ok {
		r0 = rf(ctx, notificationID)
	} else {
		r0 = ret.Get(0).(model.NotificationModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, notificationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepositoryI_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockNotificationRepositoryI_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - notificationID uint64
func (_e *MockNotificationRepositoryI_Expecter) FindByID(ctx interface{}, notificationID interface{}) *MockNotificationRepositoryI_FindByID_Call {
	return &MockNotificationRepositoryI_FindByID_Call{Call: _e.mock.On("FindByID", ctx, notificationID)}
}

func (_c *MockNotificationRepositoryI_FindByID_Call) Run(run func(ctx context.Context, notificationID uint64)) *MockNotificationRepositoryI_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockNotificationRepositoryI_FindByID_Call) Return(_a0 model.NotificationModel, _a1 error) *MockNotificationRepositoryI_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepositoryI_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.NotificationModel, error)) *MockNotificationRepositoryI_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByMonitorID provides a mock function with given fields: ctx, monitorID
func (_m *MockNotificationRepositoryI) FindByMonitorID(ctx context.Context, monitorID uint64) ([]model.NotificationModel, error) {
	ret := _m.Called(ctx, monitorID)

	if len(ret) == 0 {
		panic("no return value specified for FindByMonitorID")
	}

	var r0 []model.NotificationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]model.NotificationModel, error)); ok {
		return rf(ctx, monitorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []model.NotificationModel); ok {
		r0 = rf(ctx, monitorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.NotificationModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, monitorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepositoryI_FindByMonitorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByMonitorID'
type MockNotificationRepositoryI_FindByMonitorID_Call struct {
	*mock.Call
}

// FindByMonitorID is a helper method to define mock.On call
//   - ctx context.Context
//   - monitorID uint64
func (_e *MockNotificationRepositoryI_Expecter) FindByMonitorID(ctx interface{}, monitorID interface{}) *MockNotificationRepositoryI_FindByMonitorID_Call {
	return &MockNotificationRepositoryI_FindByMonitorID_Call{Call: _e.mock.On("FindByMonitorID", ctx, monitorID)}
}

func (_c *MockNotificationRepositoryI_FindByMonitorID_Call) Run(run func(ctx context.Context, monitorID uint64)) *MockNotificationRepositoryI_FindByMonitorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockNotificationRepositoryI_FindByMonitorID_Call) Return(_a0 []model.NotificationModel, _a1 error) *MockNotificationRepositoryI_FindByMonitorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepositoryI_FindByMonitorID_Call) RunAndReturn(run func(context.Context, uint64) ([]model.NotificationModel, error)) *MockNotificationRepositoryI_FindByMonitorID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, notification
func (_m *MockNotificationRepositoryI) Update(ctx context.Context, notification model.NotificationModel) (model.NotificationModel, error) {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.NotificationModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.NotificationModel) (model.NotificationModel, error)); ok {
		return rf(ctx, notification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.NotificationModel) model.NotificationModel); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Get(0).(model.NotificationModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.NotificationModel) error); ok {
		r1 = rf(ctx, notification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNotificationRepositoryI_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockNotificationRepositoryI_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - notification model.NotificationModel
func (_e *MockNotificationRepositoryI_Expecter) Update(ctx interface{}, notification interface{}) *MockNotificationRepositoryI_Update_Call {
	return &MockNotificationRepositoryI_Update_Call{Call: _e.mock.On("Update", ctx, notification)}
}

func (_c *MockNotificationRepositoryI_Update_Call) Run(run func(ctx context.Context, notification model.NotificationModel)) *MockNotificationRepositoryI_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.NotificationModel))
	})
	return _c
}

func (_c *MockNotificationRepositoryI_Update_Call) Return(_a0 model.NotificationModel, _a1 error) *MockNotificationRepositoryI_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNotificationRepositoryI_Update_Call) RunAndReturn(run func(context.Context, model.NotificationModel) (model.NotificationModel, error)) *MockNotificationRepositoryI_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationRepositoryI creates a new instance of MockNotificationRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationRepositoryI {
	mock := &MockNotificationRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
