// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cristiano-pacheco/pingo/internal/modules/monitor/model"
	mock "github.com/stretchr/testify/mock"
)

// MockHTTPMonitorRepositoryI is an autogenerated mock type for the HTTPMonitorRepositoryI type
type MockHTTPMonitorRepositoryI struct {
	mock.Mock
}

type MockHTTPMonitorRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPMonitorRepositoryI) EXPECT() *MockHTTPMonitorRepositoryI_Expecter {
	return &MockHTTPMonitorRepositoryI_Expecter{mock: &_m.Mock}
}

// AssignContacts provides a mock function with given fields: ctx, monitorID, contactIDs
func (_m *MockHTTPMonitorRepositoryI) AssignContacts(ctx context.Context, monitorID uint64, contactIDs []uint64) error {
	ret := _m.Called(ctx, monitorID, contactIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignContacts")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, []uint64) error); ok {
		r0 = rf(ctx, monitorID, contactIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHTTPMonitorRepositoryI_AssignContacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignContacts'
type MockHTTPMonitorRepositoryI_AssignContacts_Call struct {
	*mock.Call
}

// AssignContacts is a helper method to define mock.On call
//   - ctx context.Context
//   - monitorID uint64
//   - contactIDs []uint64
func (_e *MockHTTPMonitorRepositoryI_Expecter) AssignContacts(ctx interface{}, monitorID interface{}, contactIDs interface{}) *MockHTTPMonitorRepositoryI_AssignContacts_Call {
	return &MockHTTPMonitorRepositoryI_AssignContacts_Call{Call: _e.mock.On("AssignContacts", ctx, monitorID, contactIDs)}
}

func (_c *MockHTTPMonitorRepositoryI_AssignContacts_Call) Run(run func(ctx context.Context, monitorID uint64, contactIDs []uint64)) *MockHTTPMonitorRepositoryI_AssignContacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].([]uint64))
	})
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_AssignContacts_Call) Return(_a0 error) *MockHTTPMonitorRepositoryI_AssignContacts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_AssignContacts_Call) RunAndReturn(run func(context.Context, uint64, []uint64) error) *MockHTTPMonitorRepositoryI_AssignContacts_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, monitor
func (_m *MockHTTPMonitorRepositoryI) Create(ctx context.Context, monitor model.HTTPMonitorModel) (model.HTTPMonitorModel, error) {
	ret := _m.Called(ctx, monitor)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.HTTPMonitorModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.HTTPMonitorModel) (model.HTTPMonitorModel, error)); ok {
		return rf(ctx, monitor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.HTTPMonitorModel) model.HTTPMonitorModel); ok {
		r0 = rf(ctx, monitor)
	} else {
		r0 = ret.Get(0).(model.HTTPMonitorModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.HTTPMonitorModel) error); ok {
		r1 = rf(ctx, monitor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPMonitorRepositoryI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHTTPMonitorRepositoryI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - monitor model.HTTPMonitorModel
func (_e *MockHTTPMonitorRepositoryI_Expecter) Create(ctx interface{}, monitor interface{}) *MockHTTPMonitorRepositoryI_Create_Call {
	return &MockHTTPMonitorRepositoryI_Create_Call{Call: _e.mock.On("Create", ctx, monitor)}
}

func (_c *MockHTTPMonitorRepositoryI_Create_Call) Run(run func(ctx context.Context, monitor model.HTTPMonitorModel)) *MockHTTPMonitorRepositoryI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.HTTPMonitorModel))
	})
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_Create_Call) Return(_a0 model.HTTPMonitorModel, _a1 error) *MockHTTPMonitorRepositoryI_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_Create_Call) RunAndReturn(run func(context.Context, model.HTTPMonitorModel) (model.HTTPMonitorModel, error)) *MockHTTPMonitorRepositoryI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, monitorID
func (_m *MockHTTPMonitorRepositoryI) Delete(ctx context.Context, monitorID uint64) error {
	ret := _m.Called(ctx, monitorID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(ctx, monitorID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHTTPMonitorRepositoryI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHTTPMonitorRepositoryI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - monitorID uint64
func (_e *MockHTTPMonitorRepositoryI_Expecter) Delete(ctx interface{}, monitorID interface{}) *MockHTTPMonitorRepositoryI_Delete_Call {
	return &MockHTTPMonitorRepositoryI_Delete_Call{Call: _e.mock.On("Delete", ctx, monitorID)}
}

func (_c *MockHTTPMonitorRepositoryI_Delete_Call) Run(run func(ctx context.Context, monitorID uint64)) *MockHTTPMonitorRepositoryI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_Delete_Call) Return(_a0 error) *MockHTTPMonitorRepositoryI_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_Delete_Call) RunAndReturn(run func(context.Context, uint64) error) *MockHTTPMonitorRepositoryI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, page, pageSize
func (_m *MockHTTPMonitorRepositoryI) FindAll(ctx context.Context, page int, pageSize int) ([]model.HTTPMonitorModel, int64, error) {
	ret := _m.Called(ctx, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.HTTPMonitorModel
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]model.HTTPMonitorModel, int64, error)); ok {
		return rf(ctx, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []model.HTTPMonitorModel); ok {
		r0 = rf(ctx, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.HTTPMonitorModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockHTTPMonitorRepositoryI_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockHTTPMonitorRepositoryI_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - pageSize int
func (_e *MockHTTPMonitorRepositoryI_Expecter) FindAll(ctx interface{}, page interface{}, pageSize interface{}) *MockHTTPMonitorRepositoryI_FindAll_Call {
	return &MockHTTPMonitorRepositoryI_FindAll_Call{Call: _e.mock.On("FindAll", ctx, page, pageSize)}
}

func (_c *MockHTTPMonitorRepositoryI_FindAll_Call) Run(run func(ctx context.Context, page int, pageSize int)) *MockHTTPMonitorRepositoryI_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_FindAll_Call) Return(_a0 []model.HTTPMonitorModel, _a1 int64, _a2 error) *MockHTTPMonitorRepositoryI_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_FindAll_Call) RunAndReturn(run func(context.Context, int, int) ([]model.HTTPMonitorModel, int64, error)) *MockHTTPMonitorRepositoryI_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, monitorID
func (_m *MockHTTPMonitorRepositoryI) FindByID(ctx context.Context, monitorID uint64) (model.HTTPMonitorModel, error) {
	ret := _m.Called(ctx, monitorID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.HTTPMonitorModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.HTTPMonitorModel, error)); ok {
		return rf(ctx, monitorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.HTTPMonitorModel); ok {
		r0 = rf(ctx, monitorID)
	} else {
		r0 = ret.Get(0).(model.HTTPMonitorModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, monitorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPMonitorRepositoryI_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHTTPMonitorRepositoryI_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - monitorID uint64
func (_e *MockHTTPMonitorRepositoryI_Expecter) FindByID(ctx interface{}, monitorID interface{}) *MockHTTPMonitorRepositoryI_FindByID_Call {
	return &MockHTTPMonitorRepositoryI_FindByID_Call{Call: _e.mock.On("FindByID", ctx, monitorID)}
}

func (_c *MockHTTPMonitorRepositoryI_FindByID_Call) Run(run func(ctx context.Context, monitorID uint64)) *MockHTTPMonitorRepositoryI_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_FindByID_Call) Return(_a0 model.HTTPMonitorModel, _a1 error) *MockHTTPMonitorRepositoryI_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.HTTPMonitorModel, error)) *MockHTTPMonitorRepositoryI_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, monitor
func (_m *MockHTTPMonitorRepositoryI) Update(ctx context.Context, monitor model.HTTPMonitorModel) (model.HTTPMonitorModel, error) {
	ret := _m.Called(ctx, monitor)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.HTTPMonitorModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.HTTPMonitorModel) (model.HTTPMonitorModel, error)); ok {
		return rf(ctx, monitor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.HTTPMonitorModel) model.HTTPMonitorModel); ok {
		r0 = rf(ctx, monitor)
	} else {
		r0 = ret.Get(0).(model.HTTPMonitorModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.HTTPMonitorModel) error); ok {
		r1 = rf(ctx, monitor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPMonitorRepositoryI_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockHTTPMonitorRepositoryI_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - monitor model.HTTPMonitorModel
func (_e *MockHTTPMonitorRepositoryI_Expecter) Update(ctx interface{}, monitor interface{}) *MockHTTPMonitorRepositoryI_Update_Call {
	return &MockHTTPMonitorRepositoryI_Update_Call{Call: _e.mock.On("Update", ctx, monitor)}
}

func (_c *MockHTTPMonitorRepositoryI_Update_Call) Run(run func(ctx context.Context, monitor model.HTTPMonitorModel)) *MockHTTPMonitorRepositoryI_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.HTTPMonitorModel))
	})
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_Update_Call) Return(_a0 model.HTTPMonitorModel, _a1 error) *MockHTTPMonitorRepositoryI_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHTTPMonitorRepositoryI_Update_Call) RunAndReturn(run func(context.Context, model.HTTPMonitorModel) (model.HTTPMonitorModel, error)) *MockHTTPMonitorRepositoryI_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPMonitorRepositoryI creates a new instance of MockHTTPMonitorRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPMonitorRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPMonitorRepositoryI {
	mock := &MockHTTPMonitorRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
