// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cristiano-pacheco/pingo/internal/modules/monitor/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockHTTPMonitorCheckRepositoryI is an autogenerated mock type for the HTTPMonitorCheckRepositoryI type
type MockHTTPMonitorCheckRepositoryI struct {
	mock.Mock
}

type MockHTTPMonitorCheckRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHTTPMonitorCheckRepositoryI) EXPECT() *MockHTTPMonitorCheckRepositoryI_Expecter {
	return &MockHTTPMonitorCheckRepositoryI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, check
func (_m *MockHTTPMonitorCheckRepositoryI) Create(ctx context.Context, check model.HTTPMonitorCheckModel) (model.HTTPMonitorCheckModel, error) {
	ret := _m.Called(ctx, check)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.HTTPMonitorCheckModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.HTTPMonitorCheckModel) (model.HTTPMonitorCheckModel, error)); ok {
		return rf(ctx, check)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.HTTPMonitorCheckModel) model.HTTPMonitorCheckModel); ok {
		r0 = rf(ctx, check)
	} else {
		r0 = ret.Get(0).(model.HTTPMonitorCheckModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.HTTPMonitorCheckModel) error); ok {
		r1 = rf(ctx, check)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPMonitorCheckRepositoryI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockHTTPMonitorCheckRepositoryI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - check model.HTTPMonitorCheckModel
func (_e *MockHTTPMonitorCheckRepositoryI_Expecter) Create(ctx interface{}, check interface{}) *MockHTTPMonitorCheckRepositoryI_Create_Call {
	return &MockHTTPMonitorCheckRepositoryI_Create_Call{Call: _e.mock.On("Create", ctx, check)}
}

func (_c *MockHTTPMonitorCheckRepositoryI_Create_Call) Run(run func(ctx context.Context, check model.HTTPMonitorCheckModel)) *MockHTTPMonitorCheckRepositoryI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.HTTPMonitorCheckModel))
	})
	return _c
}

func (_c *MockHTTPMonitorCheckRepositoryI_Create_Call) Return(_a0 model.HTTPMonitorCheckModel, _a1 error) *MockHTTPMonitorCheckRepositoryI_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHTTPMonitorCheckRepositoryI_Create_Call) RunAndReturn(run func(context.Context, model.HTTPMonitorCheckModel) (model.HTTPMonitorCheckModel, error)) *MockHTTPMonitorCheckRepositoryI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, monitorID, from, to, page, pageSize
func (_m *MockHTTPMonitorCheckRepositoryI) FindAll(ctx context.Context, monitorID uint64, from *time.Time, to *time.Time, page int, pageSize int) ([]model.HTTPMonitorCheckModel, int64, error) {
	ret := _m.Called(ctx, monitorID, from, to, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []model.HTTPMonitorCheckModel
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, *time.Time, *time.Time, int, int) ([]model.HTTPMonitorCheckModel, int64, error)); ok {
		return rf(ctx, monitorID, from, to, page, pageSize)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, *time.Time, *time.Time, int, int) []model.HTTPMonitorCheckModel); ok {
		r0 = rf(ctx, monitorID, from, to, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.HTTPMonitorCheckModel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, *time.Time, *time.Time, int, int) int64); ok {
		r1 = rf(ctx, monitorID, from, to, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uint64, *time.Time, *time.Time, int, int) error); ok {
		r2 = rf(ctx, monitorID, from, to, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockHTTPMonitorCheckRepositoryI_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockHTTPMonitorCheckRepositoryI_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - monitorID uint64
//   - from *time.Time
//   - to *time.Time
//   - page int
//   - pageSize int
func (_e *MockHTTPMonitorCheckRepositoryI_Expecter) FindAll(ctx interface{}, monitorID interface{}, from interface{}, to interface{}, page interface{}, pageSize interface{}) *MockHTTPMonitorCheckRepositoryI_FindAll_Call {
	return &MockHTTPMonitorCheckRepositoryI_FindAll_Call{Call: _e.mock.On("FindAll", ctx, monitorID, from, to, page, pageSize)}
}

func (_c *MockHTTPMonitorCheckRepositoryI_FindAll_Call) Run(run func(ctx context.Context, monitorID uint64, from *time.Time, to *time.Time, page int, pageSize int)) *MockHTTPMonitorCheckRepositoryI_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(*time.Time), args[3].(*time.Time), args[4].(int), args[5].(int))
	})
	return _c
}

func (_c *MockHTTPMonitorCheckRepositoryI_FindAll_Call) Return(_a0 []model.HTTPMonitorCheckModel, _a1 int64, _a2 error) *MockHTTPMonitorCheckRepositoryI_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockHTTPMonitorCheckRepositoryI_FindAll_Call) RunAndReturn(run func(context.Context, uint64, *time.Time, *time.Time, int, int) ([]model.HTTPMonitorCheckModel, int64, error)) *MockHTTPMonitorCheckRepositoryI_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, checkID
func (_m *MockHTTPMonitorCheckRepositoryI) FindByID(ctx context.Context, checkID uint64) (model.HTTPMonitorCheckModel, error) {
	ret := _m.Called(ctx, checkID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.HTTPMonitorCheckModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.HTTPMonitorCheckModel, error)); ok {
		return rf(ctx, checkID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.HTTPMonitorCheckModel); ok {
		r0 = rf(ctx, checkID)
	} else {
		r0 = ret.Get(0).(model.HTTPMonitorCheckModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, checkID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHTTPMonitorCheckRepositoryI_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockHTTPMonitorCheckRepositoryI_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - checkID uint64
func (_e *MockHTTPMonitorCheckRepositoryI_Expecter) FindByID(ctx interface{}, checkID interface{}) *MockHTTPMonitorCheckRepositoryI_FindByID_Call {
	return &MockHTTPMonitorCheckRepositoryI_FindByID_Call{Call: _e.mock.On("FindByID", ctx, checkID)}
}

func (_c *MockHTTPMonitorCheckRepositoryI_FindByID_Call) Run(run func(ctx context.Context, checkID uint64)) *MockHTTPMonitorCheckRepositoryI_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockHTTPMonitorCheckRepositoryI_FindByID_Call) Return(_a0 model.HTTPMonitorCheckModel, _a1 error) *MockHTTPMonitorCheckRepositoryI_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHTTPMonitorCheckRepositoryI_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.HTTPMonitorCheckModel, error)) *MockHTTPMonitorCheckRepositoryI_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHTTPMonitorCheckRepositoryI creates a new instance of MockHTTPMonitorCheckRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHTTPMonitorCheckRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHTTPMonitorCheckRepositoryI {
	mock := &MockHTTPMonitorCheckRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
