// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	trace "go.opentelemetry.io/otel/trace"
)

// MockOtel is an autogenerated mock type for the Otel type
type MockOtel struct {
	mock.Mock
}

type MockOtel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOtel) EXPECT() *MockOtel_Expecter {
	return &MockOtel_Expecter{mock: &_m.Mock}
}

// StartSpan provides a mock function with given fields: ctx, name
func (_m *MockOtel) StartSpan(ctx context.Context, name string) (context.Context, trace.Span) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for StartSpan")
	}

	var r0 context.Context
	var r1 trace.Span
	if rf, ok := ret.Get(0).(func(context.Context, string) (context.Context, trace.Span)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) context.Context); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) trace.Span); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(trace.Span)
		}
	}

	return r0, r1
}

// MockOtel_StartSpan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSpan'
type MockOtel_StartSpan_Call struct {
	*mock.Call
}

// StartSpan is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockOtel_Expecter) StartSpan(ctx interface{}, name interface{}) *MockOtel_StartSpan_Call {
	return &MockOtel_StartSpan_Call{Call: _e.mock.On("StartSpan", ctx, name)}
}

func (_c *MockOtel_StartSpan_Call) Run(run func(ctx context.Context, name string)) *MockOtel_StartSpan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOtel_StartSpan_Call) Return(_a0 context.Context, _a1 trace.Span) *MockOtel_StartSpan_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOtel_StartSpan_Call) RunAndReturn(run func(context.Context, string) (context.Context, trace.Span)) *MockOtel_StartSpan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOtel creates a new instance of MockOtel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOtel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOtel {
	mock := &MockOtel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
