// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockValidate is an autogenerated mock type for the Validate type
type MockValidate struct {
	mock.Mock
}

type MockValidate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockValidate) EXPECT() *MockValidate_Expecter {
	return &MockValidate_Expecter{mock: &_m.Mock}
}

// Struct provides a mock function with given fields: s
func (_m *MockValidate) Struct(s interface{}) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockValidate_Struct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Struct'
type MockValidate_Struct_Call struct {
	*mock.Call
}

// Struct is a helper method to define mock.On call
//   - s interface{}
func (_e *MockValidate_Expecter) Struct(s interface{}) *MockValidate_Struct_Call {
	return &MockValidate_Struct_Call{Call: _e.mock.On("Struct", s)}
}

func (_c *MockValidate_Struct_Call) Run(run func(s interface{})) *MockValidate_Struct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockValidate_Struct_Call) Return(_a0 error) *MockValidate_Struct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockValidate_Struct_Call) RunAndReturn(run func(interface{}) error) *MockValidate_Struct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockValidate creates a new instance of MockValidate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockValidate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockValidate {
	mock := &MockValidate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
