// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockContactValidatorI is an autogenerated mock type for the ContactValidatorI type
type MockContactValidatorI struct {
	mock.Mock
}

type MockContactValidatorI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContactValidatorI) EXPECT() *MockContactValidatorI_Expecter {
	return &MockContactValidatorI_Expecter{mock: &_m.Mock}
}

// Validate provides a mock function with given fields: contactType, contactData
func (_m *MockContactValidatorI) Validate(contactType string, contactData string) error {
	ret := _m.Called(contactType, contactData)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(contactType, contactData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockContactValidatorI_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockContactValidatorI_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - contactType string
//   - contactData string
func (_e *MockContactValidatorI_Expecter) Validate(contactType interface{}, contactData interface{}) *MockContactValidatorI_Validate_Call {
	return &MockContactValidatorI_Validate_Call{Call: _e.mock.On("Validate", contactType, contactData)}
}

func (_c *MockContactValidatorI_Validate_Call) Run(run func(contactType string, contactData string)) *MockContactValidatorI_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockContactValidatorI_Validate_Call) Return(_a0 error) *MockContactValidatorI_Validate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockContactValidatorI_Validate_Call) RunAndReturn(run func(string, string) error) *MockContactValidatorI_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockContactValidatorI creates a new instance of MockContactValidatorI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContactValidatorI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContactValidatorI {
	mock := &MockContactValidatorI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
