// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cristiano-pacheco/pingo/internal/modules/identity/model"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepositoryI is an autogenerated mock type for the UserRepositoryI type
type MockUserRepositoryI struct {
	mock.Mock
}

type MockUserRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryI) EXPECT() *MockUserRepositoryI_Expecter {
	return &MockUserRepositoryI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, user
func (_m *MockUserRepositoryI) Create(ctx context.Context, user model.UserModel) (model.UserModel, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UserModel) (model.UserModel, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UserModel) model.UserModel); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(model.UserModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UserModel) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.UserModel
func (_e *MockUserRepositoryI_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepositoryI_Create_Call {
	return &MockUserRepositoryI_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepositoryI_Create_Call) Run(run func(ctx context.Context, user model.UserModel)) *MockUserRepositoryI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserModel))
	})
	return _c
}

func (_c *MockUserRepositoryI_Create_Call) Return(_a0 model.UserModel, _a1 error) *MockUserRepositoryI_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryI_Create_Call) RunAndReturn(run func(context.Context, model.UserModel) (model.UserModel, error)) *MockUserRepositoryI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepositoryI) FindByEmail(ctx context.Context, email string) (model.UserModel, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 model.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.UserModel, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.UserModel); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(model.UserModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryI_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepositoryI_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepositoryI_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepositoryI_FindByEmail_Call {
	return &MockUserRepositoryI_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepositoryI_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepositoryI_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepositoryI_FindByEmail_Call) Return(_a0 model.UserModel, _a1 error) *MockUserRepositoryI_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryI_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (model.UserModel, error)) *MockUserRepositoryI_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, userID
func (_m *MockUserRepositoryI) FindByID(ctx context.Context, userID uint64) (model.UserModel, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 model.UserModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (model.UserModel, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) model.UserModel); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(model.UserModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryI_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepositoryI_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockUserRepositoryI_Expecter) FindByID(ctx interface{}, userID interface{}) *MockUserRepositoryI_FindByID_Call {
	return &MockUserRepositoryI_FindByID_Call{Call: _e.mock.On("FindByID", ctx, userID)}
}

func (_c *MockUserRepositoryI_FindByID_Call) Run(run func(ctx context.Context, userID uint64)) *MockUserRepositoryI_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockUserRepositoryI_FindByID_Call) Return(_a0 model.UserModel, _a1 error) *MockUserRepositoryI_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryI_FindByID_Call) RunAndReturn(run func(context.Context, uint64) (model.UserModel, error)) *MockUserRepositoryI_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserActivated provides a mock function with given fields: ctx, userID
func (_m *MockUserRepositoryI) IsUserActivated(ctx context.Context, userID uint64) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserActivated")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepositoryI_IsUserActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserActivated'
type MockUserRepositoryI_IsUserActivated_Call struct {
	*mock.Call
}

// IsUserActivated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockUserRepositoryI_Expecter) IsUserActivated(ctx interface{}, userID interface{}) *MockUserRepositoryI_IsUserActivated_Call {
	return &MockUserRepositoryI_IsUserActivated_Call{Call: _e.mock.On("IsUserActivated", ctx, userID)}
}

func (_c *MockUserRepositoryI_IsUserActivated_Call) Run(run func(ctx context.Context, userID uint64)) *MockUserRepositoryI_IsUserActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockUserRepositoryI_IsUserActivated_Call) Return(_a0 bool, _a1 error) *MockUserRepositoryI_IsUserActivated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepositoryI_IsUserActivated_Call) RunAndReturn(run func(context.Context, uint64) (bool, error)) *MockUserRepositoryI_IsUserActivated_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, user
func (_m *MockUserRepositoryI) Update(ctx context.Context, user model.UserModel) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UserModel) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepositoryI_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepositoryI_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.UserModel
func (_e *MockUserRepositoryI_Expecter) Update(ctx interface{}, user interface{}) *MockUserRepositoryI_Update_Call {
	return &MockUserRepositoryI_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *MockUserRepositoryI_Update_Call) Run(run func(ctx context.Context, user model.UserModel)) *MockUserRepositoryI_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserModel))
	})
	return _c
}

func (_c *MockUserRepositoryI_Update_Call) Return(_a0 error) *MockUserRepositoryI_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepositoryI_Update_Call) RunAndReturn(run func(context.Context, model.UserModel) error) *MockUserRepositoryI_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepositoryI creates a new instance of MockUserRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryI {
	mock := &MockUserRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
