// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	enum "github.com/cristiano-pacheco/pingo/internal/modules/identity/enum"
	mock "github.com/stretchr/testify/mock"

	model "github.com/cristiano-pacheco/pingo/internal/modules/identity/model"
)

// MockOneTimeTokenRepositoryI is an autogenerated mock type for the OneTimeTokenRepositoryI type
type MockOneTimeTokenRepositoryI struct {
	mock.Mock
}

type MockOneTimeTokenRepositoryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOneTimeTokenRepositoryI) EXPECT() *MockOneTimeTokenRepositoryI_Expecter {
	return &MockOneTimeTokenRepositoryI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockOneTimeTokenRepositoryI) Create(ctx context.Context, token model.OneTimeTokenModel) (model.OneTimeTokenModel, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.OneTimeTokenModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.OneTimeTokenModel) (model.OneTimeTokenModel, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.OneTimeTokenModel) model.OneTimeTokenModel); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(model.OneTimeTokenModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.OneTimeTokenModel) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOneTimeTokenRepositoryI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOneTimeTokenRepositoryI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token model.OneTimeTokenModel
func (_e *MockOneTimeTokenRepositoryI_Expecter) Create(ctx interface{}, token interface{}) *MockOneTimeTokenRepositoryI_Create_Call {
	return &MockOneTimeTokenRepositoryI_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockOneTimeTokenRepositoryI_Create_Call) Run(run func(ctx context.Context, token model.OneTimeTokenModel)) *MockOneTimeTokenRepositoryI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.OneTimeTokenModel))
	})
	return _c
}

func (_c *MockOneTimeTokenRepositoryI_Create_Call) Return(_a0 model.OneTimeTokenModel, _a1 error) *MockOneTimeTokenRepositoryI_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOneTimeTokenRepositoryI_Create_Call) RunAndReturn(run func(context.Context, model.OneTimeTokenModel) (model.OneTimeTokenModel, error)) *MockOneTimeTokenRepositoryI_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, userID, tokenTypeEnum
func (_m *MockOneTimeTokenRepositoryI) Delete(ctx context.Context, userID uint64, tokenTypeEnum enum.TokenTypeEnum) error {
	ret := _m.Called(ctx, userID, tokenTypeEnum)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, enum.TokenTypeEnum) error); ok {
		r0 = rf(ctx, userID, tokenTypeEnum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOneTimeTokenRepositoryI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOneTimeTokenRepositoryI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - tokenTypeEnum enum.TokenTypeEnum
func (_e *MockOneTimeTokenRepositoryI_Expecter) Delete(ctx interface{}, userID interface{}, tokenTypeEnum interface{}) *MockOneTimeTokenRepositoryI_Delete_Call {
	return &MockOneTimeTokenRepositoryI_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, tokenTypeEnum)}
}

func (_c *MockOneTimeTokenRepositoryI_Delete_Call) Run(run func(ctx context.Context, userID uint64, tokenTypeEnum enum.TokenTypeEnum)) *MockOneTimeTokenRepositoryI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(enum.TokenTypeEnum))
	})
	return _c
}

func (_c *MockOneTimeTokenRepositoryI_Delete_Call) Return(_a0 error) *MockOneTimeTokenRepositoryI_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOneTimeTokenRepositoryI_Delete_Call) RunAndReturn(run func(context.Context, uint64, enum.TokenTypeEnum) error) *MockOneTimeTokenRepositoryI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, userID, tokenTypeEnum
func (_m *MockOneTimeTokenRepositoryI) Find(ctx context.Context, userID uint64, tokenTypeEnum enum.TokenTypeEnum) (model.OneTimeTokenModel, error) {
	ret := _m.Called(ctx, userID, tokenTypeEnum)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 model.OneTimeTokenModel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, enum.TokenTypeEnum) (model.OneTimeTokenModel, error)); ok {
		return rf(ctx, userID, tokenTypeEnum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, enum.TokenTypeEnum) model.OneTimeTokenModel); ok {
		r0 = rf(ctx, userID, tokenTypeEnum)
	} else {
		r0 = ret.Get(0).(model.OneTimeTokenModel)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, enum.TokenTypeEnum) error); ok {
		r1 = rf(ctx, userID, tokenTypeEnum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOneTimeTokenRepositoryI_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockOneTimeTokenRepositoryI_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
//   - tokenTypeEnum enum.TokenTypeEnum
func (_e *MockOneTimeTokenRepositoryI_Expecter) Find(ctx interface{}, userID interface{}, tokenTypeEnum interface{}) *MockOneTimeTokenRepositoryI_Find_Call {
	return &MockOneTimeTokenRepositoryI_Find_Call{Call: _e.mock.On("Find", ctx, userID, tokenTypeEnum)}
}

func (_c *MockOneTimeTokenRepositoryI_Find_Call) Run(run func(ctx context.Context, userID uint64, tokenTypeEnum enum.TokenTypeEnum)) *MockOneTimeTokenRepositoryI_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64), args[2].(enum.TokenTypeEnum))
	})
	return _c
}

func (_c *MockOneTimeTokenRepositoryI_Find_Call) Return(_a0 model.OneTimeTokenModel, _a1 error) *MockOneTimeTokenRepositoryI_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOneTimeTokenRepositoryI_Find_Call) RunAndReturn(run func(context.Context, uint64, enum.TokenTypeEnum) (model.OneTimeTokenModel, error)) *MockOneTimeTokenRepositoryI_Find_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOneTimeTokenRepositoryI creates a new instance of MockOneTimeTokenRepositoryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOneTimeTokenRepositoryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOneTimeTokenRepositoryI {
	mock := &MockOneTimeTokenRepositoryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
