// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/cristiano-pacheco/pingo/pkg/kafka"
	mock "github.com/stretchr/testify/mock"
)

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockConsumer) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConsumer_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConsumer_Expecter) Close() *MockConsumer_Close_Call {
	return &MockConsumer_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConsumer_Close_Call) Run(run func()) *MockConsumer_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConsumer_Close_Call) Return(_a0 error) *MockConsumer_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_Close_Call) RunAndReturn(run func() error) *MockConsumer_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Consume provides a mock function with given fields: ctx, handler
func (_m *MockConsumer) Consume(ctx context.Context, handler kafka.MessageHandler) error {
	ret := _m.Called(ctx, handler)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, kafka.MessageHandler) error); ok {
		r0 = rf(ctx, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockConsumer_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - ctx context.Context
//   - handler kafka.MessageHandler
func (_e *MockConsumer_Expecter) Consume(ctx interface{}, handler interface{}) *MockConsumer_Consume_Call {
	return &MockConsumer_Consume_Call{Call: _e.mock.On("Consume", ctx, handler)}
}

func (_c *MockConsumer_Consume_Call) Run(run func(ctx context.Context, handler kafka.MessageHandler)) *MockConsumer_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(kafka.MessageHandler))
	})
	return _c
}

func (_c *MockConsumer_Consume_Call) Return(_a0 error) *MockConsumer_Consume_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_Consume_Call) RunAndReturn(run func(context.Context, kafka.MessageHandler) error) *MockConsumer_Consume_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
