// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	service "github.com/cristiano-pacheco/pingo/internal/modules/identity/service"
	mock "github.com/stretchr/testify/mock"
)

// MockEmailTemplateServiceI is an autogenerated mock type for the EmailTemplateServiceI type
type MockEmailTemplateServiceI struct {
	mock.Mock
}

type MockEmailTemplateServiceI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailTemplateServiceI) EXPECT() *MockEmailTemplateServiceI_Expecter {
	return &MockEmailTemplateServiceI_Expecter{mock: &_m.Mock}
}

// CompileAccountConfirmationTemplate provides a mock function with given fields: input
func (_m *MockEmailTemplateServiceI) CompileAccountConfirmationTemplate(input service.AccountConfirmationInput) (string, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for CompileAccountConfirmationTemplate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(service.AccountConfirmationInput) (string, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(service.AccountConfirmationInput) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(service.AccountConfirmationInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompileAccountConfirmationTemplate'
type MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call struct {
	*mock.Call
}

// CompileAccountConfirmationTemplate is a helper method to define mock.On call
//   - input service.AccountConfirmationInput
func (_e *MockEmailTemplateServiceI_Expecter) CompileAccountConfirmationTemplate(input interface{}) *MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call {
	return &MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call{Call: _e.mock.On("CompileAccountConfirmationTemplate", input)}
}

func (_c *MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call) Run(run func(input service.AccountConfirmationInput)) *MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(service.AccountConfirmationInput))
	})
	return _c
}

func (_c *MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call) Return(_a0 string, _a1 error) *MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call) RunAndReturn(run func(service.AccountConfirmationInput) (string, error)) *MockEmailTemplateServiceI_CompileAccountConfirmationTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// CompileAuthVerificationCodeTemplate provides a mock function with given fields: name, code
func (_m *MockEmailTemplateServiceI) CompileAuthVerificationCodeTemplate(name string, code string) (string, error) {
	ret := _m.Called(name, code)

	if len(ret) == 0 {
		panic("no return value specified for CompileAuthVerificationCodeTemplate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(name, code)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(name, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(name, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompileAuthVerificationCodeTemplate'
type MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call struct {
	*mock.Call
}

// CompileAuthVerificationCodeTemplate is a helper method to define mock.On call
//   - name string
//   - code string
func (_e *MockEmailTemplateServiceI_Expecter) CompileAuthVerificationCodeTemplate(name interface{}, code interface{}) *MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call {
	return &MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call{Call: _e.mock.On("CompileAuthVerificationCodeTemplate", name, code)}
}

func (_c *MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call) Run(run func(name string, code string)) *MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call) Return(_a0 string, _a1 error) *MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call) RunAndReturn(run func(string, string) (string, error)) *MockEmailTemplateServiceI_CompileAuthVerificationCodeTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmailTemplateServiceI creates a new instance of MockEmailTemplateServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailTemplateServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailTemplateServiceI {
	mock := &MockEmailTemplateServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
