// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/cristiano-pacheco/pingo/internal/modules/identity/model"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenServiceI is an autogenerated mock type for the TokenServiceI type
type MockTokenServiceI struct {
	mock.Mock
}

type MockTokenServiceI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenServiceI) EXPECT() *MockTokenServiceI_Expecter {
	return &MockTokenServiceI_Expecter{mock: &_m.Mock}
}

// GenerateJWT provides a mock function with given fields: ctx, user
func (_m *MockTokenServiceI) GenerateJWT(ctx context.Context, user model.UserModel) (string, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateJWT")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.UserModel) (string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.UserModel) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.UserModel) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenServiceI_GenerateJWT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateJWT'
type MockTokenServiceI_GenerateJWT_Call struct {
	*mock.Call
}

// GenerateJWT is a helper method to define mock.On call
//   - ctx context.Context
//   - user model.UserModel
func (_e *MockTokenServiceI_Expecter) GenerateJWT(ctx interface{}, user interface{}) *MockTokenServiceI_GenerateJWT_Call {
	return &MockTokenServiceI_GenerateJWT_Call{Call: _e.mock.On("GenerateJWT", ctx, user)}
}

func (_c *MockTokenServiceI_GenerateJWT_Call) Run(run func(ctx context.Context, user model.UserModel)) *MockTokenServiceI_GenerateJWT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.UserModel))
	})
	return _c
}

func (_c *MockTokenServiceI_GenerateJWT_Call) Return(_a0 string, _a1 error) *MockTokenServiceI_GenerateJWT_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenServiceI_GenerateJWT_Call) RunAndReturn(run func(context.Context, model.UserModel) (string, error)) *MockTokenServiceI_GenerateJWT_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenServiceI creates a new instance of MockTokenServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenServiceI {
	mock := &MockTokenServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
