// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/cristiano-pacheco/pingo/internal/modules/identity/service"
	mock "github.com/stretchr/testify/mock"
)

// MockSendEmailConfirmationService is an autogenerated mock type for the SendEmailConfirmationService type
type MockSendEmailConfirmationService struct {
	mock.Mock
}

type MockSendEmailConfirmationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSendEmailConfirmationService) EXPECT() *MockSendEmailConfirmationService_Expecter {
	return &MockSendEmailConfirmationService_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockSendEmailConfirmationService) Execute(ctx context.Context, input service.SendEmailConfirmationInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.SendEmailConfirmationInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSendEmailConfirmationService_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSendEmailConfirmationService_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input service.SendEmailConfirmationInput
func (_e *MockSendEmailConfirmationService_Expecter) Execute(ctx interface{}, input interface{}) *MockSendEmailConfirmationService_Execute_Call {
	return &MockSendEmailConfirmationService_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockSendEmailConfirmationService_Execute_Call) Run(run func(ctx context.Context, input service.SendEmailConfirmationInput)) *MockSendEmailConfirmationService_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.SendEmailConfirmationInput))
	})
	return _c
}

func (_c *MockSendEmailConfirmationService_Execute_Call) Return(_a0 error) *MockSendEmailConfirmationService_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSendEmailConfirmationService_Execute_Call) RunAndReturn(run func(context.Context, service.SendEmailConfirmationInput) error) *MockSendEmailConfirmationService_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSendEmailConfirmationService creates a new instance of MockSendEmailConfirmationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSendEmailConfirmationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSendEmailConfirmationService {
	mock := &MockSendEmailConfirmationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
