// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/cristiano-pacheco/pingo/internal/modules/identity/service"
	mock "github.com/stretchr/testify/mock"
)

// MockSendEmailVerificationCodeServiceI is an autogenerated mock type for the SendEmailVerificationCodeServiceI type
type MockSendEmailVerificationCodeServiceI struct {
	mock.Mock
}

type MockSendEmailVerificationCodeServiceI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSendEmailVerificationCodeServiceI) EXPECT() *MockSendEmailVerificationCodeServiceI_Expecter {
	return &MockSendEmailVerificationCodeServiceI_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockSendEmailVerificationCodeServiceI) Execute(ctx context.Context, input service.SendEmailVerificationCodeInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.SendEmailVerificationCodeInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSendEmailVerificationCodeServiceI_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockSendEmailVerificationCodeServiceI_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input service.SendEmailVerificationCodeInput
func (_e *MockSendEmailVerificationCodeServiceI_Expecter) Execute(ctx interface{}, input interface{}) *MockSendEmailVerificationCodeServiceI_Execute_Call {
	return &MockSendEmailVerificationCodeServiceI_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockSendEmailVerificationCodeServiceI_Execute_Call) Run(run func(ctx context.Context, input service.SendEmailVerificationCodeInput)) *MockSendEmailVerificationCodeServiceI_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.SendEmailVerificationCodeInput))
	})
	return _c
}

func (_c *MockSendEmailVerificationCodeServiceI_Execute_Call) Return(_a0 error) *MockSendEmailVerificationCodeServiceI_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSendEmailVerificationCodeServiceI_Execute_Call) RunAndReturn(run func(context.Context, service.SendEmailVerificationCodeInput) error) *MockSendEmailVerificationCodeServiceI_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSendEmailVerificationCodeServiceI creates a new instance of MockSendEmailVerificationCodeServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSendEmailVerificationCodeServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSendEmailVerificationCodeServiceI {
	mock := &MockSendEmailVerificationCodeServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
