// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserActivationServiceI is an autogenerated mock type for the UserActivationServiceI type
type MockUserActivationServiceI struct {
	mock.Mock
}

type MockUserActivationServiceI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserActivationServiceI) EXPECT() *MockUserActivationServiceI_Expecter {
	return &MockUserActivationServiceI_Expecter{mock: &_m.Mock}
}

// IsUserActivated provides a mock function with given fields: ctx, userID
func (_m *MockUserActivationServiceI) IsUserActivated(ctx context.Context, userID uint64) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsUserActivated")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserActivationServiceI_IsUserActivated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserActivated'
type MockUserActivationServiceI_IsUserActivated_Call struct {
	*mock.Call
}

// IsUserActivated is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint64
func (_e *MockUserActivationServiceI_Expecter) IsUserActivated(ctx interface{}, userID interface{}) *MockUserActivationServiceI_IsUserActivated_Call {
	return &MockUserActivationServiceI_IsUserActivated_Call{Call: _e.mock.On("IsUserActivated", ctx, userID)}
}

func (_c *MockUserActivationServiceI_IsUserActivated_Call) Run(run func(ctx context.Context, userID uint64)) *MockUserActivationServiceI_IsUserActivated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockUserActivationServiceI_IsUserActivated_Call) Return(_a0 bool, _a1 error) *MockUserActivationServiceI_IsUserActivated_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserActivationServiceI_IsUserActivated_Call) RunAndReturn(run func(context.Context, uint64) (bool, error)) *MockUserActivationServiceI_IsUserActivated_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserActivationServiceI creates a new instance of MockUserActivationServiceI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserActivationServiceI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserActivationServiceI {
	mock := &MockUserActivationServiceI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
