// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockUserActivatedCacheI is an autogenerated mock type for the UserActivatedCacheI type
type MockUserActivatedCacheI struct {
	mock.Mock
}

type MockUserActivatedCacheI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserActivatedCacheI) EXPECT() *MockUserActivatedCacheI_Expecter {
	return &MockUserActivatedCacheI_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: userID
func (_m *MockUserActivatedCacheI) Delete(userID uint64) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserActivatedCacheI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserActivatedCacheI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - userID uint64
func (_e *MockUserActivatedCacheI_Expecter) Delete(userID interface{}) *MockUserActivatedCacheI_Delete_Call {
	return &MockUserActivatedCacheI_Delete_Call{Call: _e.mock.On("Delete", userID)}
}

func (_c *MockUserActivatedCacheI_Delete_Call) Run(run func(userID uint64)) *MockUserActivatedCacheI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockUserActivatedCacheI_Delete_Call) Return(_a0 error) *MockUserActivatedCacheI_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserActivatedCacheI_Delete_Call) RunAndReturn(run func(uint64) error) *MockUserActivatedCacheI_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: userID
func (_m *MockUserActivatedCacheI) Get(userID uint64) (bool, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(uint64) (bool, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint64) bool); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserActivatedCacheI_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockUserActivatedCacheI_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID uint64
func (_e *MockUserActivatedCacheI_Expecter) Get(userID interface{}) *MockUserActivatedCacheI_Get_Call {
	return &MockUserActivatedCacheI_Get_Call{Call: _e.mock.On("Get", userID)}
}

func (_c *MockUserActivatedCacheI_Get_Call) Run(run func(userID uint64)) *MockUserActivatedCacheI_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockUserActivatedCacheI_Get_Call) Return(_a0 bool, _a1 error) *MockUserActivatedCacheI_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserActivatedCacheI_Get_Call) RunAndReturn(run func(uint64) (bool, error)) *MockUserActivatedCacheI_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: userID
func (_m *MockUserActivatedCacheI) Set(userID uint64) error {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserActivatedCacheI_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockUserActivatedCacheI_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - userID uint64
func (_e *MockUserActivatedCacheI_Expecter) Set(userID interface{}) *MockUserActivatedCacheI_Set_Call {
	return &MockUserActivatedCacheI_Set_Call{Call: _e.mock.On("Set", userID)}
}

func (_c *MockUserActivatedCacheI_Set_Call) Run(run func(userID uint64)) *MockUserActivatedCacheI_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockUserActivatedCacheI_Set_Call) Return(_a0 error) *MockUserActivatedCacheI_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserActivatedCacheI_Set_Call) RunAndReturn(run func(uint64) error) *MockUserActivatedCacheI_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserActivatedCacheI creates a new instance of MockUserActivatedCacheI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserActivatedCacheI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserActivatedCacheI {
	mock := &MockUserActivatedCacheI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
