// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	rsa "crypto/rsa"
)

// MockPrivateKeyRegistryI is an autogenerated mock type for the PrivateKeyRegistryI type
type MockPrivateKeyRegistryI struct {
	mock.Mock
}

type MockPrivateKeyRegistryI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrivateKeyRegistryI) EXPECT() *MockPrivateKeyRegistryI_Expecter {
	return &MockPrivateKeyRegistryI_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with no fields
func (_m *MockPrivateKeyRegistryI) Get() *rsa.PrivateKey {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *rsa.PrivateKey
	if rf, ok := ret.Get(0).(func() *rsa.PrivateKey); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rsa.PrivateKey)
		}
	}

	return r0
}

// MockPrivateKeyRegistryI_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPrivateKeyRegistryI_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockPrivateKeyRegistryI_Expecter) Get() *MockPrivateKeyRegistryI_Get_Call {
	return &MockPrivateKeyRegistryI_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockPrivateKeyRegistryI_Get_Call) Run(run func()) *MockPrivateKeyRegistryI_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPrivateKeyRegistryI_Get_Call) Return(_a0 *rsa.PrivateKey) *MockPrivateKeyRegistryI_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPrivateKeyRegistryI_Get_Call) RunAndReturn(run func() *rsa.PrivateKey) *MockPrivateKeyRegistryI_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrivateKeyRegistryI creates a new instance of MockPrivateKeyRegistryI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrivateKeyRegistryI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrivateKeyRegistryI {
	mock := &MockPrivateKeyRegistryI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
